### ISSUE TITLE
Direct pip install throws binary incompatibility error

### ISSUE THREAD

**Issue by debadeepta** [automl/nasbench301#12]
If I do directly `pip install nasbench301` it throws an error when I go to execute the example.

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

```
(nasbench301) REDMOND.dedey@GCRAZGDL0459:~/nasbench301$ python nasbench301/example.py 
Traceback (most recent call last):
  File "nasbench301/example.py", line 4, in <module>
    from ConfigSpace.read_and_write import json as cs_json
  File "/home/dedey/.local/lib/python3.8/site-packages/ConfigSpace/__init__.py", line 37, in <module>
    from ConfigSpace.configuration_space import Configuration, \
  File "ConfigSpace/configuration_space.pyx", line 39, in init ConfigSpace.configuration_space
  File "__init__.pxd", line 242, in init ConfigSpace.hyperparameters
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by debadeepta** [comment]
This was again due to using python 3.8. On python 3.7 it doesn't throw this error but I have new errors I am investigating.
