### ISSUE TITLE
Hyperparameter 'q'

### ISSUE THREAD

**Issue by AnaRisnoveanu** [automl/nasbench301#20]
I am running into an error when calling example.py. Do you know what could cause this?

`==> Loading performance surrogate model...

c:\Users\nasbench301\nb_models_0.9\xgb_v0.9
Traceback (most recent call last):

  File "c:/Users/nasbench301/example.py", line 38, in <module>
    performance_model = nb.load_ensemble(ensemble_dir_performance)
  File "C:\Users\nasbench301\api.py", line 56, in load_ensemble
    surrogate_model.load(model_paths=ensemble_member_dirs)
  File "C:\Users\nasbench301\surrogate_models\ensemble.py", line 119, in load
    ens_mem = utils.model_dict[self.member_model_name](log_dir=None, seed=self.starting_seed+ind, **self.member_model_init_dict)
  File "C:\Users\nasbench301\surrogate_models\gradient_boosting\xgboost.py", line 13, in __init__
    super(XGBModel, self).__init__(data_root, log_dir, seed, model_config, data_config)
  File "C:\Users\nasbench301\surrogate_models\surrogate_model.py", line 31, in __init__
    self.config_loader = utils.ConfigLoader(configspace_path)
  File "C:\Users\nasbench301\surrogate_models\utils.py", line 83, in __init__
    self.config_space = self.load_config_space(config_space_path)
  File "C:\Users\nasbench301\surrogate_models\utils.py", line 153, in load_config_space
    config_space = config_space_json_r_w.read(json_string)
  File "C:\Users\miniconda3\envs\NASLib\lib\site-packages\ConfigSpace\read_and_write\json.py", line 444, in read
    _construct_hyperparameter(
  File "C:\Users\miniconda3\envs\NASLib\lib\site-packages\ConfigSpace\read_and_write\json.py", line 524, in _construct_hyperparameter
    q=hyperparameter["q"],
KeyError: 'q'`

**Comment by hjh3169** [comment]
I also encountered this problem. Any solution?

**Comment by AnaRisnoveanu** [comment]
Unfortunately, no, @hjh3169 :( I moved on to another TransNasBench101.

**Comment by hjh3169** [comment]
> Unfortunately, no, @hjh3169 :( I moved on to another TransNasBench101.

Hi, I found the reason. Higher versions of ConfigSpace seem to cause this error. You can try a lower version, like 0.5.0

**Comment by arberzela** [comment]
Hi AnaRisnoveanu, sorry for the late reply and thank you for pointing out this issue. As hjh3169 mentioned you need to use an older version of ConfigSpace. I updated the requirements.txt file accordingly.
